@extends('themes.default.auth.layout')

@section('title')
    @lang('l.Two-Factor Authentication')
@endsection

@section('description')
@endsection

@section('page-css')
@endsection


@section('content')
    <div class="authentication-inner row m-0">
        <!-- /Left Text -->
        <div class="d-none d-lg-flex col-lg-7 col-xl-8 align-items-center p-5">
            <div class="w-100 d-flex justify-content-center">
                <img src="{{ asset('assets/themes/default/img/illustrations/boy-verify-email-light.png') }}"
                    class="img-fluid" alt="Login image" width="700"
                    data-app-dark-img="illustrations/boy-verify-email-dark.png"
                    data-app-light-img="illustrations/boy-verify-email-light.png" />
            </div>
        </div>
        <!-- /Left Text -->

        <!--  Verify email -->
        <div class="d-flex col-12 col-lg-5 col-xl-4 align-items-center authentication-bg p-6 p-sm-12">
            <div class="w-px-400 mx-auto mt-12 mt-5">
                <h4 class="mb-3 text-center">
                    @lang('l.Two-Factor Authentication')
                    <i class="fa-brands fa-google ms-2"
                        style="background: linear-gradient(90deg, #4285f4 25%, #34a853 25%, #34a853 50%, #fbbc05 50%, #fbbc05 75%, #ea4335 75%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;"></i>
                </h4>
                <div class="alert alert-info mb-4">
                    @lang('l.Please enter the 6-digit code generated by your authenticator app to complete the two-factor authentication process.')
                </div>
                @if (session('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif
                @if ($errors->any())
                    <div class="alert alert-danger">
                        {{ $errors->first() }}
                    </div>
                @endif
                <form method="POST" action="{{ route('2fa.verify') }}" class="mb-4">
                    @csrf
                    <div class="mb-3">
                        <label class="form-label" for="code">{{ __('l.Verification Code') }}</label>
                        <input type="text" name="code" id="code" class="form-control form-control-lg" required
                            maxlength="6" pattern="\d{6}" placeholder="000000"
                            style="letter-spacing: 0.3em; text-align: center; font-size: 1.2em;">
                    </div>
                    <button type="submit" class="btn btn-primary d-block w-100 btn-lg">
                        <i class="fas fa-shield-alt me-2"></i>
                        {{ __('l.Verify') }}
                    </button>
                </form>
                <div class="text-center">
                    <small class="text-muted">@lang('l.or')</small>
                    <form method="POST" action="{{ route('logout') }}" class="mt-2">
                        @csrf
                        <button type="submit" class="btn btn-link text-danger">
                            <i class="fas fa-sign-out-alt me-1"></i>
                            @lang('l.Logout')
                        </button>
                    </form>
                </div>
            </div>
        </div>
        <!-- / Verify email -->
    </div>
@endsection


@section('page-scripts')
@endsection
